# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'cnk' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for cnk

  #pod 'GooglePlaces'
  pod 'GoogleMaps'
  #pod 'Google/SignIn'
  #pod 'GooglePlacePicker'

  target 'cnk-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'cnkTests' do
    inherit! :search_paths
    # Pods for testing
  end


end
